name: Staging Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy to staging
        run: |
          curl -X POST https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }} -d [{"key":"DATABASE_URL_INTERNAL","value":"${{ secrets.DATABASE_URL_INTERNAL }}"}]
          curl -X GET https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
  
  deploy_prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: deploy_staging
    steps:
      - name: Deploy to prod
        run: |
          curl -X GET https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

  