name: CI/CD Pipeline

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop, master ]

jobs:
  unit_tests:
    # Run for both pull requests into develop and pushes to develop/master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Run unit tests
        run: dotnet test --verbosity normal --settings tests.runsettings

  deploy_staging:
    # Run after unit_tests if pushing to develop
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    needs: unit_tests
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy to staging
        run: |
          curl -X GET https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

  deploy_prod:
    # Run after deploy_staging if pushing to master
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: deploy_staging
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy to prod
        run: |
          curl -X GET https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
