name: CI/CD Pipeline

on:
  pull_request:
    branches: [ develop, master ]

jobs:
  unit_tests:
    if: github.base_ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.2'
      - name: Restore dependencies
        run: dotnet restore
      - name: Run unit tests
        run: dotnet test normal --settings tests.runsettings

  deploy_staging:
    needs: unit_tests
    if: github.base_ref == 'develop'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy to staging
        run: |
          curl -X GET https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

  deploy_prod:
    if: github.base_ref == 'master' && github.head_ref == 'develop'
    needs: deploy_staging
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy to prod
        run: |
          curl -X GET https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
